name: Devcontainer
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

permissions:
  contents: read

jobs:
  devcontainer-test:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft != true
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          show-progress: false

      - name: Build and run dev container task
        uses: devcontainers/ci@b63b30de439b47a52267f241112c5b453b673db5 # v0.3.1900000449
        with:
          runCmd: pnpm build
